# Generated by Django 2.2.19 on 2023-05-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='topic',
        ),
    ]
