# Generated by Django 2.2.19 on 2023-05-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230508_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanInAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='счетчик')),
                ('ip', models.GenericIPAddressField(verbose_name='ip')),
                ('is_ban', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BanInAuth',
            },
        ),
    ]
