# Generated by Django 2.2.19 on 2023-05-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_baninauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_ban',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
        migrations.AddField(
            model_name='profile',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
