# Generated by Django 2.2.19 on 2023-05-23 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230523_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reason_ban',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
